# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

test:
  S3_BUCKET: storkypics
  S3_ID: AKIAJVTVIWXJEUZHYSSQ
  S3_SECRET: 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
  MC_API_KEY: 7dddce689b91442e55e1c815dcede9d7-us6
development:
  S3_BUCKET: storkypics
  S3_ID: AKIAJVTVIWXJEUZHYSSQ
  S3_SECRET: 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
  MC_API_KEY: 7dddce689b91442e55e1c815dcede9d7-us6
staging:
  S3_BUCKET: storkypics
  S3_ID: AKIAJVTVIWXJEUZHYSSQ
  S3_SECRET: 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
  MC_API_KEY: 7dddce689b91442e55e1c815dcede9d7-us6
production:
  S3_BUCKET: storkypics
  S3_ID: AKIAJVTVIWXJEUZHYSSQ
  S3_SECRET: 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
  MC_API_KEY: 7dddce689b91442e55e1c815dcede9d7-us6